---

- name: Create Downloads directory
  file:
    path: /home/vagrant/Downloads
    state: directory
    owner: vagrant

- name: Download Tor Browser package
  get_url:
    url: https://www.torproject.org/dist/torbrowser/13.0/tor-browser-linux-x86_64-13.0.tar.xz
    dest: /home/vagrant/Downloads/tor-browser-linux-x86_64-13.0.tar.xz
    mode: '500'
    checksum: sha512:b0e72d4af5009510ca3129e35c0ebb7a379ab2c289a196bfc9372baba2c4b531b079fd6baf5d287993e1761cf1c6d51ed5a5476cfe7237edb8f5d28bc22c0c37
    owner: vagrant

- name: Create Desktop directory
  file:
    path: /home/vagrant/Desktop
    state: directory
    owner: vagrant    

- name: Extract Tor Browser package
  unarchive:
    src: /home/vagrant/Downloads/tor-browser-linux-x86_64-13.0.tar.xz
    dest: /home/vagrant/Desktop
    remote_src: yes
    owner: vagrant
    mode: '700'
